# StarWise/docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8530:8000"
    volumes:
      - ./starwise_data:/app/data
    env_file:
      - ./backend/.env  # <--- Change this line to point to the new file
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3530:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local # <--- Add this line for the frontend
    restart: unless-stopped

volumes:
  starwise_data:
    driver: local
